


---
- name: Fail if required settings are not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == '' or vars[item] == []"
  with_items:
    - "ca_mode"
    - "ca_common_name"

- name: Running mode ca
  include_tasks: ca.yaml
  when:
    - ca_mode == 'ca'

- name: Running mode copy
  include_tasks: copy.yaml
  when:
    - ca_mode == 'copy'